

* My dotfiles
These are my personal configurations for various applications. I will keep this as up-to-date as I can. Don't even try to understand these, they are kind of a mess tbh.


* Table of Contents :TOC:
- [[#my-dotfiles][My dotfiles]]
- [[#installation][Installation]]
- [[#notes][Notes]]

* Installation :TOC: 
For most of these programs, the installation is quite simple - copy the =.config= folder into your =~/.config= folder. For bash, I do have conda installed for my data science class, but don't feel like you have to use it - you are free to delete that section from the bashrc. You will need to install [[https://regolith-linux.org/][Regolith Linux]] for the window manager - I highly recommend it for someone new to tiling WMs.  

 
* Notes :TOC:
 - You will need to create a subdirectory in ~/Music and call it alerts. Find a wav file you like and save it as alert.wav in the alerts directory. I am using [[http://soundbible.com/2154-Text-Message-Alert-1.html][this]] as my alert sound, but use whatever you want.
 - The dictionary goes in =~/.vim/spell/=
 - I am using Chemacs2 for handling my emacs profiles. Follow the default installation instructions it has.
