# ls aliases
alias ls="exa --color=auto"
alias la="exa -la"
alias ll="exa -lah"
alias lsr="exa -alhrs modified"
#Navigation and Clearing Aliases
alias home="cd /home/jhilker"
alias rm="rm -rfi"
alias Linux="cd ~/LinuxConfig; exa -alh"
alias dynworld="cd /home/jhilker/Documents/RPGs/dynasticworld; emacs dynastic-world.org"
alias mkdir="mkdir -p"
alias cp="cp -r"
alias cl='[ $[$RANDOM % 100] = 0 ] && timeout 6 cbeams -o; clear || clear'
# alias clear='[ $[$RANDOM % 10] = 0 ] && timeout 6 cbeams -o; clear || clear'
#alias cl="clear"
#alias rm="rm -rfi"
alias clock="clear; echo -e 'It is $(date +%I:%M) $(date +%p) on $(date +%a), $(date '+%e %b').'"
alias font="fc-cache -f -v"
alias mutt="mbsync -a && neomutt; ref"
alias proc="ytop -m"
alias ref="source ~/.zshrc"
alias wx="curl 'wttr.in?format=3'"
#alias neomutt="neomutt; cl; ref"
#alias newsboat="newsboat; cl; ref"
alias news="newsboat -r; ref"
#alias wxm="curl wttr.in?format=3"
alias update="sudo apt update -y"
alias upgrade="sudo apt update && sudo apt upgrade -y"
#alias install="sudo apt install -y"
alias autoremove="sudo apt autoremove -y"
alias purge="sudo apt purge -y"
alias fix="sudo dpkg --configure -a"
alias music="tizonia --spotify-playlist-id https://open.spotify.com/playlist/69uvLQBtqvAMoyNFPy7ErL -s --spotify-allow-explicit-tracks"
alias code="tizonia --spotify-playlist-id https://open.spotify.com/playlist/0sSrQJpH4B00xG7bPDrJXp -s --spotify-allow-explicit-tracks"
alias erb="tizonia --spotify-playlist-id https://open.spotify.com/playlist/0tpXl15JsHSKrHx4TgSbOy -s --spotify-allow-explicit-tracks"
alias geb="tizonia --spotify-playlist-id 'https://open.spotify.com/playlist/3iSNMhp2CnftVz43VA5lwP' -s"
alias iks="tizonia --spotify-album 'In Keeping Secrets of Silent Earth 3' --spotify-allow-explicit-tracks"
alias ga4="tizonia --spotify-album-id 'https://open.spotify.com/album/4nYsnQpTAQaPzrPc6rOsBN' --spotify-allow-explicit-tracks"
alias nwft="tizonia --spotify-album 'No World For Tomorrow' --spotify-allow-explicit-tracks"
alias study="tizonia --spotify-playlist-id 'https://open.spotify.com/playlist/37i9dQZF1DX8Uebhn9wzrS' -s --spotify-allow-explicit-tracks"
alias lmus="tizonia -rs ~/Music"
alias shp="tizonia --spotify-album-id 'https://open.spotify.com/album/7hgb44Kiav8NRoa26nuus5' --spotify-allow-explicit-tracks"
alias coheed="tizonia --spotify-artist coheed --spotify-allow-explicit-tracks -s"
alias inquiryum="tizonia --youtube-audio-playlist 'https://www.youtube.com/playlist?list=PLuZfoSIficQvPRuNhFHPcFpYsWy9Wb3iQ'"
alias swing='tizonia --youtube-audio-playlist "https://www.youtube.com/playlist?list=PLVKACZpRqh76r-zJLvIvojhg4pudPnJcV" -s'
alias jazz="tizonia --youtube-audio-playlist 'https://www.youtube.com/playlist?list=PLc2FAW0Ie_V7q2mtrV-0xGDe3-G8d9YyP' -s"
alias doom="tizonia --spotify-album 'Doom (Original Game Soundtrack)' --spotify-allow-explicit-tracks"
alias cuphead="tizonia --spotify-album 'Cuphead (Original Soundtrack)' --spotify-allow-explicit-tracks"
alias desktop="cd ~/Desktop"
alias documents="cd ~/Documents"
alias dropbox="cd ~/Dropbox"
alias pictures="cd ~/Pictures"
alias download="cd ~/Downloads"
alias tunes="cd ~/Music"
alias conf="cd ~/.config"
alias cache="cd ~/.cache"
alias dots="cd ~/Documents/dotfiles"
alias asgn="cd ~/Documents/assignments; exa -alhrs modified"

alias cs350="cd ~/Documents/assignments/cpsc350" 
# Programming Aliases
alias jdcomp=" sudo javadoc -d directory (/var/www/html) -private *.java"
alias gpom="git push origin master"
alias gpull="git pull"
alias gcln="git clone"
alias commit="git add *; git commit -a"
alias commitm="git add *; git commit -am"
alias clone="git clone"
alias vim="vim -u ~/.config/vim/vimrc"
#alias python="python3.8"
#writing, worldbuilding, and rpg aliases
alias Ashes="cd ~/Documents/Ashes-World; exa -alh"
##alias AshesWrite="cd ~/Ashes-World/writing; exa -alh"
##alias AshesCampaign="cd ~/Ashes-World/campaigns; exa -alh"
alias Aurea="cd ~/DOcumentsAurea-World; exa -alh"
##alias AureaCampaign="cd ~/Aurea-World/campaigns; exa -alh"
##alias AureaLore="emacs ~/Aurea-World/lore/lore.org"
alias Kidal="cd ~/Documents/Kidal; exa -alh"
##alias KidalLore="emacs ~/Kidal/lore/lore.org"
##alias hunt="emacs ~/Ashes-World/campaigns/the-great-hunt/greatHunt.org"
##alias campaign="cd ~/solo-campaigns; exa -alh"

# Game Aliases
alias els="rlwrap telnet elessar.mudhosting.net 7778"
alias sol="rlwrap telnet Middle-earth.us 4500"
alias 2048="~/2048"

# Timer Aliases
alias pom="termdown 25m -b -s"
alias pos="termdown 5m -b -s"
alias pol="termdown 20m -b -s"

