#!/bin/sh

# 1 - state index
# 2 - state
# 3 - total cases
# 4 - new cases 
# 5 - total deaths
# 6 - new deaths
# 7 - Active Cases 

[ "$(stat -c %y ~/.cache/corona | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
  curl -sL "https://corona-stats.online/states/US" > ~/.cache/corona
#grep "State\|Virginia" ~/.cache/corona | sed -n 1p | sed "s/\s*//g ; s/║//g ; s/│/;/g" |
#  awk -F';' '{print $4}'

grep "State\|Virginia" ~/.cache/corona | sed -n 2p | sed "s/\s*//g ; s/║//g ; s/│/;/g" |
  awk -F';' '{print "😷 " $3   "  󰲇  "  $4  " (🕱 " $6 ")"}' 

#  '{print   "󰲇  "  $4  " (🕱 " $6 ")" }'  



# 1
# 2 
# 3 
# 4 
# 5 
# 6 
# 7
#curl -sL https://corona-stats.online/states/US?minimal=true > ~/.cache/corona
#grep "Virginia" ~/.cache/corona | sed -n 1p | awk '{print $2}'
