#!/bin/sh 
#vi :set filetype=sh 
if [ -z $1 ] 
then
termdown -Bs 25m && notify-send -a "Pomodoro" "Timer Done" "Take a break. You've earned it."; for sound in $(seq 1); 
do $(aplay -q ~/Music/alerts/alert.wav);
done

elif [ $1 = "-s" ] || [ $1 = "--short" ]
then
termdown -Bs 5m && notify-send -a "Pomodoro" "Timer Done" "Take a break. You've earned it."; for sound in $(seq 1); 
do $(aplay -q ~/Music/alerts/alert.wav);
done

elif [ $1 = "-l" ] || [ $1 = "--long" ]
then
termdown -Bs 5m && notify-send -a "Pomodoro" "Timer Done" "Take a break. You've earned it."; for sound in $(seq 1); 
do $(aplay -q ~/Music/alerts/alert.wav);
done                                                                                                                elif [ $1 = "-h" ]  || [ $1 = "--help" ] 
then
 echo "usage: pomo           25 minute timer"

 echo "or:    pomo [options] see options below\n"
 echo "-s, --short:     5 minute break timer"
 echo "-l, --long:      20 minute break timer" 
 echo "-h, --help:     view this help message"
fi 
