#! /bin/sh

sxhkd &
xrdb -load ~/.Xresources
xrandr --size 1360x768
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
picom -b --opacity-rule 75:"class_g *= 'XTerm'" &
rofication-daemon & 
feh --bg-center ~/Pictures/Wallpapers/scheme-based/gruvbox/dark/pacman-soft.png
$HOME/.config/polybar/launch.sh

bspc config border_width         3
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#dd2727"

bspc config border_radius 4


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


