#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb -load ~/.Xresources
xrandr --size 1360x768
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
picom -b --opacity-rule 75:"class_g *= 'XTerm'" &
rofication-daemon & 
feh --bg-center ~/Pictures/Wallpapers/scheme-based/gruvbox/dark/pacman.png
$HOME/.config/polybar/launch.sh


bspc rule --add Gimp desktop='^8' state=floating follow=on
bspc rule --add Chromium desktop='^2'
bspc rule --add mplayer2 state=floating
bspc rule --add Kupfer.py focus=on
bspc rule --add Screenkey manage=off
bspc rule --add Zathura -state=tiled

bspc config border_width         4
bspc config window_gap          20
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color	"#32302f"
bspc config active_border_color	"#282828"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color "#cc241d"

bspc config border_radius 4


