#! /bin/sh


bspc config border_width         2
bspc config window_gap           8 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#928374'
bspc config focused_border_color '#ebdbb2'
bspc config presel_border_color '#d79921'
bspc config normal_sticky_border_color '#4e4e4e'
bspc config focused_sticky_border_color '#83a598'
bspc config urgent_border_color '#fb4934'

bspc config border_radius 4

bspc monitor -d 1 2 3 4 5 6 7 8 9 10


bspc rule --add Gimp desktop='^8' state=floating follow=on
bspc rule --add Chromium desktop='^2'
bspc rule --add mplayer2 state=floating
bspc rule --add Kupfer.py focus=on
bspc rule --add Screenkey manage=off
bspc rule --add Zathura state=tiled
bspc rule --add conky state=floating manage=off
pgrep -x sxhkd > /dev/null || sxhkd &
xrdb -load ~/.Xresources
xrandr --size 1360x768
picom -b --opacity-rule 75:"class_g *= 'XTerm'" &
rofication-daemon & 
feh --bg-center ~/Pictures/Wallpapers/scheme-based/gruvbox/dark/pacman.png
$HOME/.config/polybar/launch.sh

pgrep bspswallow || bspswallow &
