#!/bin/bash 
 
rofi -no-lazy-grab -sep "|" -dmenu -i -p 'System :' \
-hide-scrollbar true \
-bw 0 \
-lines 5 \
-line-padding 10 \
-padding 20 \
-width 15 \
\
\
-columns 1 \
\
-font "Iosevka 12" \
<<< "Sleep  |Lock  |Logout  |Reboot  |Shutdown "
case "$MENU" in
  *Sleep) systemctl suspend ;;
  *Lock) gnome-scrensaver-command --lock ;;
  *Logout) /usr/bin/gnome-session-quit --logout ;;
  *Reboot) /usr/bin/gnome-session-quit --reboot ;;
  *Shutdown) /usr/bin/gnome-session-quit --power-off ;;
esac
