#+title: Jmacs (Jacob's Literate Emacs Config)
#+author: Jacob Hilker
#+startup: fold

* Table of Contents :toc:
- [[#introduction-to-jmacs][*Introduction to JMACS*]]
  - [[#personal-info][Personal Info]]
- [[#package-setup][Package Setup]]
  - [[#using-melpa][Using Melpa]]
  - [[#using-org][Using Org]]
  - [[#most-important-packages][Most Important Packages]]
- [[#packages][Packages]]
  - [[#code-packages][Code Packages]]
  - [[#ui-packages][UI Packages]]
  - [[#org-mode-packages][Org Mode Packages]]
  - [[#elfeed][Elfeed]]
- [[#misc-functions][Misc. Functions]]
  - [[#edit-dotfile][Edit Dotfile]]
- [[#org-mode-config][Org Mode Config]]
  - [[#agenda-files][Agenda Files]]
  - [[#keywords][Keywords]]
  - [[#faces][Faces]]
  - [[#source-code-formatting][Source Code Formatting]]
  - [[#custom-agenda-commands][Custom Agenda Commands]]
- [[#ui-tweaks][UI Tweaks]]
  - [[#minimalist-ui][Minimalist UI]]
  - [[#fonts][Fonts]]
  - [[#org-mode-ui][Org Mode UI]]
  - [[#custom-faces][Custom Faces]]
- [[#keybindings][Keybindings]]
  - [[#general-keybindings][General Keybindings]]
  - [[#file-keybindings][File Keybindings]]
  - [[#org-mode-keybindings][Org-Mode Keybindings]]
  - [[#elfeed-keybindings][Elfeed Keybindings]]
  - [[#misc-keybindings][Misc. Keybindings]]
  - [[#tab-indents][Tab Indents]]
- [[#minor-tweaks][Minor Tweaks]]
  - [[#disable-indent-on-newlines][Disable Indent on Newlines]]

* *Introduction to JMACS*
Welcome to JMacs! This is a my personal configuration of emacs, for solo RPG campaigns like [[https://www.ironswornrpg.com/][Ironsworn]], writing (both prose and code), and for general use. I have organized this file into different sections, such as the functions I use, the UI settings, etc.
** Personal Info
   #+BEGIN_SRC emacs-lisp
(setq user-full-name "Jacob Hilker"
      user-mail-address "jacob.hilker2@gmail.com")
   #+END_SRC

* Package Setup
** Using Melpa
   I want to add melpa to my package list.
   #+begin_src emacs-lisp
(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))
(package-refresh-contents)
(package-initialize)
   #+END_src
** Using Org
   I want to add the org-mode repositories to my package list as well.
   #+begin_src emacs-lisp
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/"))
   #+end_src
** Most Important Packages
These are the most important functions I practically need to function in Emacs.
*** Use-Package
    Use-Package allows me to bootstrap my package loading very easily. 
    #+begin_src emacs-lisp
(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)
    #+end_src
*** Undo Tree
    Lets me use more of evil-modes undo functionality.
    #+begin_src emacs-lisp
    (use-package undo-tree
    :config
     (global-undo-tree-mode))
    #+end_src
*** Evil Mode
    Evil mode lets me use the (superior) Vim bindings to the Emacs ones. In addition, I don't want =:q= to kill emacs, but rather the current buffer I am in (similar to Vim).
    #+begin_src emacs-lisp
(use-package evil
  :init
  (setq evil-undo-system 'undo-tree)

  (setq evil-want-integration t) ;; This is optional since it's already set to t by default.
  (setq evil-want-keybinding nil)
  :config
  ;(evil-set-undo-system 'undo-tree)
  ;(setq evil-undo-system 'undo-tree)
  (evil-mode 1)
  :preface
  (defun ian/save-and-kill-this-buffer ()
    (interactive)
    (save-buffer)
    (kill-this-buffer))
  :config
  (with-eval-after-load 'evil-maps ; avoid conflict with company tooltip selection
    (define-key evil-insert-state-map (kbd "C-n") nil)
    (define-key evil-insert-state-map (kbd "C-p") nil))
  (evil-ex-define-cmd "q" #'kill-this-buffer)
  (evil-ex-define-cmd "wq" #'ian/save-and-kill-this-buffer))

(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))

(use-package evil-surround
  :config
  (global-evil-surround-mode 1))
    #+end_src
*** General
    General lets me define my own keybindings.
    #+begin_src emacs-lisp
(use-package general)
    #+end_src
*** Org Plus Contrib
    The updated version of org-mode.
    #+begin_src emacs-lisp
(use-package org
  :ensure org-plus-contrib)
    #+end_src
**** Old Structure Shortcuts
     #+begin_src emacs-lisp
(use-package org-tempo
				 :ensure nil)
     #+end_src
*** Which-Key
Which-Key allows me to see the keybindings I have available at a glance.
#+begin_src emacs-lisp
(use-package which-key
:config
(which-key-mode 1))
#+end_src
* Packages
** Code Packages
   This section contains all the packages I use for code and for projects.
*** Projectile
    Projectile allows me to manage projects in emacs.
    #+begin_src emacs-lisp
(use-package projectile
:config
(projectile-mode)
(setq projectile-project-search-path '("~/Projects/" "~/Documents/aurea" "~/Documents/brokenThrones" "~/Documents/byrne" "~/Documents/shatteredSkies")))
    #+end_src
*** Completion Packages
**** Ivy
     #+begin_src emacs-lisp
(use-package ivy
 :config
 (setq ivy-count-format "(%d/%d) ")
 (ivy-mode 1))
#+end_src
**** Swiper
**** Counsel
**** Company
*** Formatting Packages
**** Smartparens 
		 #+begin_src emacs-lisp
     (use-package smartparens)
		 #+end_src
*** Git
Magit is probably tthe second killer feature of emacs, behind org-mode.
#+begin_src emacs-lisp
(use-package magit)
(use-package magit-todos)
#+end_src
** UI Packages
*** Themes
**** Gruvbox Theme
     What can I say, I love gruvbox.
     #+begin_src emacs-lisp
       (use-package gruvbox-theme)
       ;(load-theme 'gruvbox-dark-medium t)
     #+end_src
**** Doom Themes
     Doom Themes is an excellent collection of themes.
     #+begin_src emacs-lisp
(use-package doom-themes)
(setq doom-themes-enable-italic t
      doom-themes-enable-bold t)
(load-theme 'doom-gruvbox t)
     #+end_src
*** Doom Modeline
    This lets me set up a clean modeline.
    #+begin_src emacs-lisp
(use-package doom-modeline
  :config
  (setq doom-modeline-height 32))
(doom-modeline-mode 1)
    #+end_src
*** All The Icons
    All-the-icons allows me to have icons in emacs.
    #+begin_src emacs-lisp
(use-package all-the-icons)
    #+end_src
*** Dashboard
    Dashboard allows me to have a simple dashboard as a startup buffer.
    #+begin_src emacs-lisp
(use-package dashboard
  :config
  (dashboard-setup-startup-hook)) 
    #+end_src
    In addition to that, I'd like to use it as the default buffer when I start up emacsclient.
    #+begin_src emacs-lisp
(setq initial-buffer-choice (lambda () (get-buffer "*dashboard*")))
    #+end_src
*** Centaur Tabs
    #+begin_src emacs-lisp
    (use-package centaur-tabs
    :config
    (centaur-tabs-mode t)
		(setq centaur-tabs-set-modified-marker t
					centaur-tabs-modified-marker "•"
					centaur-tabs-set-bar 'left
					centaur-tabs-set-icons t
					centaur-tabs-set-close-button t
					centaur-tabs-close-button "x"
					centaur-tabs-style "bar"
					centaur-tabs-cycle-scope 'tabs)
		(define-key evil-normal-state-map (kbd "g t") 'centaur-tabs-forward)
    (define-key evil-normal-state-map (kbd "g T") 'centaur-tabs-backward))
    #+end_src
** Org Mode Packages
*** Org Super Agenda
    Org Super agenda is such a nice package that I love to use. It essentially allows me to reorganize my agenda much more easily than in regular Elisp.
    #+begin_src emacs-lisp
    (use-package org-super-agenda
    :config
    (add-hook 'org-mode-hook 'org-super-agenda-mode))
    #+end_src
*** TOC Org
    This package allows me to add a table of contents to an org-mode file.
    #+begin_src emacs-lisp
(use-package toc-org
:config
(toc-org-mode 1))
    #+end_src
*** Org-Bullets
This package makes my bullets look nicer.
#+begin_src emacs-lisp
(use-package org-bullets
:after org)
(add-hook 'org-mode-hook 'org-bullets-mode)
#+end_src
*** Org-Mode Export Backends
**** Ox-Hugo  
		 I use Hugo for my static site generator, and want to have it as a backend for my website.
		 #+begin_src emacs-lisp
(use-package ox-hugo
	:after ox)
		 #+end_src
**** Ox-Pandoc
Pandoc is my go-to program when I need a different format.
#+begin_src emacs-lisp
(use-package ox-pandoc
	:after ox)
#+end_src 
** Elfeed 
Elfeed is an RSS reader for emacs.
#+begin_src emacs-lisp
(defun elfeed-mark-all-as-read ()
	(interactive)
  (mark-whole-buffer)
  (elfeed-search-untag-all-unread))

(use-package elfeed
	:config
	(setq elfeed-db-directory "~/.elfeed/"
				 elfeed-search-filter "@1-week-ago +unread "	
				 elfeed-show-mode-hook
           (lambda ()
						 (set-face-attribute 'variable-pitch (selected-frame) :font (font-spec :family "Iosevka" :size 16))))

	:bind (:map elfeed-search-mode-map
	  ("A" . elfeed-mark-all-as-read)))

(use-package elfeed-org
	:after elfeed
	:config
	(elfeed-org)
	(setq rmh-elfeed-org-files (list "~/Dropbox/org/elfeed.org")))

(use-package elfeed-goodies 
	:after elfeed
	:config
	(elfeed-goodies/setup)
	 (setq elfeed-goodies/feed-source-column-width 30))
#+end_src
*** UI Tweaks 
**** Custom Print Function
		 #+begin_src emacs-lisp
     (defun jh/elfeed-search-print-entry (entry)
  "Print ENTRY to the buffer."
  (let* ((elfeed-goodies/tag-column-width 40)
         (elfeed-goodies/feed-source-column-width 30)
         (title (or (elfeed-meta entry :title) (elfeed-entry-title entry) ""))
         (title-faces (elfeed-search--faces (elfeed-entry-tags entry)))
         (feed (elfeed-entry-feed entry))
         (feed-title
          (when feed
            (or (elfeed-meta feed :title) (elfeed-feed-title feed))))
         (tags (mapcar #'symbol-name (elfeed-entry-tags entry)))
         (tags-str (concat (mapconcat 'identity tags ",")))

         (title-width (- (window-width) 10 elfeed-search-trailing-width))
         (title-column (elfeed-format-column
                        title (elfeed-clamp
                               elfeed-search-title-min-width
                               title-width
                               elfeed-search-title-max-width)
                        :left))

         (tag-column (elfeed-format-column
                      tags-str (elfeed-clamp (length tags-str)
                                             elfeed-goodies/tag-column-width
                                             elfeed-goodies/tag-column-width)
                      :left))

         (feed-column (elfeed-format-column
                       feed-title (elfeed-clamp elfeed-goodies/feed-source-column-width
                                                elfeed-goodies/feed-source-column-width
                                                elfeed-goodies/feed-source-column-width)
                       :left)))


    (insert (propertize title-column 'face title-faces 'kbd-help title) " ")
    (insert (propertize feed-column 'face 'elfeed-search-feed-face) " ")
    (insert (propertize tag-column 'face 'elfeed-search-tag-face) " ")
    (setq-local line-spacing 0.2)))

		 #+end_src
* Misc. Functions
** Edit Dotfile
A quick shortcut to let me edit my dotfile.
#+begin_src emacs-lisp
(defun edit-dotfile () 
(interactive)
(find-file "~/.emacs.d/jmacs.org"))
#+end_src
* Org Mode Config
** Agenda Files
I personally only use my class notes file and my personal agenda file as my agenda. I'm setting those up here.
#+begin_src emacs-lisp
(setq org-agenda-files (list "~/Dropbox/org/agenda.org" "~/Dropbox/notes/spring2021.org"))
#+end_src
** Keywords
This is what I use for my to-do list keywords. Org-mode scheduling is probably the feature I use the most in org-mode. I want to set up my keywords here, so I don’t need to do it in every file.
#+begin_src emacs-lisp
(setq org-todo-keywords '(
      (sequence "TODO(t)" "INPR(i)" "NEXT(n)" "MEET(m)" "|" "SOMEDAY(s)"   "DONE(d)" "CANCELED(c)")
      (type "PROJ(p)")
      (type "BLOG(b)")))
#+end_src
** Faces
I want to set up specific colors for each keyword here. Red for todo, etc.
#+begin_src emacs-lisp
(setq org-todo-keyword-faces
 '(
   ("TODO" . (:foreground "#cc241d" :weight black :underline t))
   ("INPR" . (:foreground "#fe8019" :weight bold))
   ("NEXT" . (:foreground "#fabd2f" :weight black))
   ("MEET" . (:foreground "#b8bb26" :weight bold))
   ("PROJ" . (:foreground "#458588" :slant italic :weight bold))
   ("BLOG" . (:foreground "#83a598"))
   ("SOMEDAY" . (:foreground "#d3869b" :slant italic))
   ("DONE" . (:foreground "#83a598" :strike-through t))
   ("CANCELED" . (:foreground "cc241d" :strike-through t))))
;   ("DONE" . "green")

#+end_src
** Source Code Formatting
I don't like having org-mode auto indent code.
*** Preserving Indentation
This forces org-babel to save my indentation.
#+begin_src emacs-lisp
(setq org-src-preserve-indentation t)
#+end_src
*** Recognizing the Tab Key
    I want my tab key to indent source code.
#+begin_src emacs-lisp
(setq org-src-tab-acts-natively t
			org-edit-src-content-indentation 0)
#+end_src
*** Disabling Warning Days
I want to see exactly when something is due, rather than a warning period.
#+begin_src emacs-lisp
(setq org-deadline-warning-days 0)
#+end_src
** Custom Agenda Commands
*** Planner
    I personally love this block agenda.
    #+begin_src emacs-lisp
(add-to-list 'org-agenda-custom-commands
	     '("p" "Planner"
	       (
		(agenda "" ((org-agenda-span 'day)
			    (org-agenda-use-time-grid t)
			    (org-agenda-time-grid '((daily today weekly require-timed)()() "" nil))
			    (org-agenda-show-all-dates t)
			    (org-agenda-compact-blocks nil)
			    (org-agenda-overriding-header "")
			    (org-agenda-start-day "+0d")
			    (org-super-agenda-groups
			     '(
			       (:name "Habits"
				      :habit t
				      :category "HABIT"
				      :order 2)
			       
			       (:name "Chores"
				      :habit t
				      :category "CHORE"
				      :order 2)



			       (:name none
				      :discard (:todo "DONE")
				      :time-grid t
				      :date today
				      :scheduled today
				      :deadline today
				      :order 1)))))

                   (agenda "" ((org-agenda-overriding-header "Coming Up Soon") 
                       ;(org-agenda-prefix-format '((todo . " %i %-22:c %t %22(org-entry-get nil \"TIMESTAMP\")")))
;                       (org-agenda-skip-function '(org-agenda-skip-entry-if 'nottimestamp))
	                ; 
                      ; (org-agenda-use-time-grid nil) 
                      ; (org-agenda-time-grid '((daily today weekly require-timed)()() "----------------------" nil))
		               (org-agenda-start-day "+1d")
     ;                   (org-agenda-todo-ignore-with-date t)
                      ; (org-agenda-format-date "\n%d %b (%a.)\n")
                      
									 (org-agenda-time-grid '((daily today weekly require-timed)()() "" nil))
                   (org-agenda-format-date "\n%d %b (%a.)")
			;		   (concat (make-string (window-width) 9472) "\n")
             ;         (org-agenda-compact-blocks t)
                   (org-agenda-span 2)
																				;(org-agenda-format-date "%d %b")
                   (org-super-agenda-groups
                    '(
                      
                      (:name "Habits"
                         :habit t
                         :category "HABIT"
                         :order 6)
                         
                         (:name "Chores"
                         :habit t
                         :category "CHORE"
                         :order 6)
                         

     ;                 (:name "Projects"
     ;                 :category "PROJECT"
     ;                 :order 5)
                      
                     
    (:name "Personal"
    :category ("WRITING" "CAMPAIGN" "PERSONAL" "NANO" "UMWCLUB")
    :order 4)
    
;    
;    (:name "Someday"
;     :and (:not (:category ("WRITING" "CAMPAIGN" "PERSONAL" "NANO")) :todo "SOMEDAY")
;     :order 5)

    (:name "Overdue"
      :deadline past
      :scheduled past
      :face '(:foreground "red")
      :order 3)
;
;
    (:name "Classwork and Meetings"
     :category ("CPSC430" "DGST101" "CPSC414" "CPSC444" "MEETING")
     :order 1)))))

				 (alltodo "" ((org-agenda-overriding-header "To Do")
                  (org-agenda-skip-function '(org-agenda-skip-entry-if 'timestamp))
                  (org-agenda-sorting-strategy '(todo-state-up category-up ))
                  (org-super-agenda-groups '(
                  (:name "Classwork and Meetings"
                  :category ("CLAS204" "CPSC405" "CPSC419" "CPSC445" "MEETING" "CLASSES")
                  :order 1)
                 
                  (:name "Personal"
                  :category ("WRITING" "CAMPAIGN" "PERSONAL" "NANO" "UMWCLUB")
                  :order 2)
                  
                  (:name "Projects"
                   :todo "PROJECT"
                   :category "PROJECT"
                   :order 3)
                  

                 (:discard (:category "HABIT"))
                 (:discard (:category "CHORE")))))))))


		    #+end_src
**** Helper Function 
		 This is a helper function for quickly opening my preferred agenda view.
		 #+begin_src emacs-lisp
(defun jh/open-planner ()
(interactive)
(org-agenda nil "p"))
		 #+end_src
*** 
* UI Tweaks
  This section contains the general UI settings - not for any specific program.
** Minimalist UI
   Here is where I make my UI as minimalistic as possible. I am disabling
   my toolbars, tooltip-mode, menu-bar, and scroll-bar modes here.
   #+begin_src emacs-lisp
(scroll-bar-mode -1)
(tool-bar-mode -1)
(tooltip-mode -1)
(menu-bar-mode -1)
   #+end_src
** Fonts
   I personally love Iosevka Nerd font.
*** Setting The Font Face
    #+begin_src emacs-lisp
(set-face-attribute 'default nil
  :font "Iosevka Nerd Font"
  :height 120)
    #+end_src
*** Increasing Font Size in Emacsclient
    #+begin_src emacs-lisp
;; Needed if using emacsclient. Otherwise, your fonts will be smaller than expected.
(add-to-list 'default-frame-alist '(font . "Iosevka Nerd Font-12"))
#+end_src
*** Adding Pretty Icons to Text
    This sets up so that something like =lamba= will be rendered as a pretty character.
    #+begin_src emacs-lisp
;; changes certain keywords to symbols, such as lamda!
(setq global-prettify-symbols-mode t)
    #+end_src

    #+end_src
*** Line Numbers and Truncated Lines
    #+begin_src emacs-lisp
;(global-display-line-numbers-mode 1)
;(global-visual-line-mode t)

    #+end_src
** Org Mode UI
*** Bullets 
    #+begin_src emacs-lisp
(setq org-bullets-bullet-list '("⚫" "○")) 
    #+end_src
**** Use a Bullet as the Heading 
     #+begin_src emacs-lisp
(font-lock-add-keywords 'org-mode
                        '(("^ +\\([-*]\\) "
                           (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
     #+end_src
*** Formatting Characters
I don't want to see any formatting characters.
#+begin_src emacs-lisp
(setq org-hide-emphasis-markers t)
#+end_src
*** Ellipsis
I want an arrow for the ellipsis instead of the three dots.
#+begin_src emacs-lisp
(setq org-ellipsis "⤵")
#+end_src
*** Italics and Bold
    #+begin_src emacs-lisp
(set-face-attribute 'font-lock-comment-face nil
  :slant 'italic)
    #+end_src
** Custom Faces
*** Gruvbox Theme
I want the first four levels of headings to be bold.
#+begin_src emacs-lisp
;(set-face-attribute 'org-level-1 nil :weight 'bold)
;(set-face-attribute 'org-level-2 nil :weight 'bold )
;(set-face-attribute 'org-level-3 nil :weight 'bold )
;(set-face-attribute 'org-level-4 nil :weight 'bold)
#+end_src
*** Doom Gruvbox
I like having different colors for each face of a heading.
#+begin_src emacs-lisp
(set-face-attribute 'org-level-1 nil :foreground "#83a598")
(set-face-attribute 'org-level-2 nil :foreground "#d3869b")
(set-face-attribute 'org-level-3 nil :foreground "#fabd2f")
(set-face-attribute 'org-level-4 nil :foreground "#fb4934")
(set-face-attribute 'org-level-5 nil :foreground "#83a598" :weight 'regular)
(set-face-attribute 'org-level-6 nil :foreground "#d3869b" :weight 'regular)
(set-face-attribute 'org-level-7 nil :foreground "#fabd2f" :weight 'regular)
(set-face-attribute 'org-level-8 nil :foreground "#fb4934" :weight 'regular)
#+end_src
* Keybindings
** General Keybindings
   I want to use =Spc spc= for running =M-x=, etc. Similar to spacemacs.
     #+begin_src emacs-lisp
(general-define-key
   :states '(normal visual insert emacs)
   :prefix "SPC"
   :non-normal-prefix "C-SPC"

    "SPC" (general-simulate-key "M-x")
    "c"   (general-simulate-key "C-c")
    "h"   (general-simulate-key "C-h")
    "u"   (general-simulate-key "C-u")
    "x"   (general-simulate-key "C-x"))

     #+end_src
** File Keybindings
   #+begin_src emacs-lisp
(general-define-key
   :states '(normal visual insert emacs)
   :prefix "SPC"
   :non-normal-prefix "C-SPC"


   "f" '(:ignore t :which-key "Files")
	 "fed" '(edit-dotfile :which-key "Edit Config")
   "ff" '(find-file :which-key "Find file")
   "fs" '(save-buffer :which-key "Save file")
   "fl" '(load-file :which-key "Load file"))
   #+end_src
** Org-Mode Keybindings
These are all my org-mode bindings.
#+begin_src emacs-lisp
(general-define-key
   :states '(normal visual insert emacs)
   :prefix "SPC"
   :non-normal-prefix "C-SPC"

	 "o" '(:ignore t :which-key "Org-mode")
	 "oa" '(jh/open-planner :which-key "Open agenda")
	 "oA" '(org-agenda :which-key "Open agenda dispatch")
	 "oe" '(org-export-dispatch :which-key "Export org file")
	 "ob" '(org-babel-tangle :which-key "Babel tangle"))
#+end_src
** Elfeed Keybindings
	 This is a shortcut for me to get to elfeed. In addition, it has shortcuts for me to get to different filters.
	 #+begin_src emacs-lisp
(general-define-key
   :states '(normal visual insert emacs)
   :prefix "SPC"
   :non-normal-prefix "C-SPC"
	  "n" '(:ignore t :which-key "News")
		"nn" '(elfeed :which-key "Read news"))
(evil-define-key 'normal elfeed-search-mode-map (kbd "A") 'elfeed-mark-all-as-read)
	 #+end_src
** Misc. Keybindings
*** Zoom In And Out
I want to use =C-=== and =C--= to zoom text in and out.
   #+begin_src emacs-lisp
(global-set-key (kbd "C-=") 'text-scale-increase)
(global-set-key (kbd "C--") 'text-scale-decrease)

   #+end_src
** Tab Indents
	 Since I can't seem to get the tab key to indent properly this is where it goes until I fix it.
   #+begin_src emacs-lisp
;(setq indent-tabs-mode nil)
(setq-default tab-width 2)

(general-define-key
 :states '(normal insert visual emacs)
    "TAB" 'indent-for-tab-command)

;;(global-set-key (kbd "TAB") 'tab-to-tab-stop) ;; works - but in normal mode too.

   #+end_src
* Minor Tweaks
** Disable Indent on Newlines
   If I really wanted to indent newlines, I'd do it myself.
   #+begin_src emacs-lisp
(setq electric-indent-mode nil)
   #+end_src
   
